name: sample
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is test"
      - uses: actions/checkout@v2
      - run: |
          ls -la
          cd .github/workflows/
          ls -la